/**
 * Background harbor traffic from AIS (see src/lib/ais.ts): one box per
 * vessel in the real ship's reported dimensions, colored by its AIS type,
 * plus a name label. Positions dead-reckon along course and speed between
 * the ~30 s polls, so moving ships glide instead of hopping. The city
 * ferries are excluded upstream – they sail as simulated vehicles whose
 * positions the AIS override corrects (overrideFerryPositions).
 *
 * Same rendering approach as VehicleLayer: Primitive boxes with in-place
 * modelMatrix updates (Entity boxes rebuild geometry asynchronously and
 * freeze under continuous movement), a plain text label per vessel.
 */

import {
  BoundingSphere,
  BoxGeometry,
  CustomShader,
  Model,
  UniformType,
  Cartesian2,
  Cartesian3,
  Color,
  ColorGeometryInstanceAttribute,
  ConstantPositionProperty,
  ConstantProperty,
  DistanceDisplayCondition,
  GeometryInstance,
  HeadingPitchRoll,
  Intersect,
  LabelStyle,
  Math as CesiumMath,
  Matrix4,
  PerInstanceColorAppearance,
  Primitive,
  Transforms,
  type Entity,
  type Viewer,
} from 'cesium'
import { AIS_EXPIRE_MS, AIS_RECKON_CAP_MS, deadReckon, type AisVessel } from '@/lib/ais-extract'

export interface VesselLayerHost {
  requestRender(): void
  /** Ellipsoid height of the water surface (calibrated like the ferry routes). */
  readonly waterSurfaceHeight: number
}

/** Ship names fade in below this camera distance (meters). */
const NAME_VISIBLE_RANGE = 15_000
/**
 * Beyond this camera distance a moving vessel does not request repaints –
 * at 20 km a hull is sub-pixel, and the app's event-driven rendering must
 * stay idle when nothing visible changes (the trams' layer works the same
 * way: movement only costs GPU while it is inside the view).
 */
const VESSEL_RENDER_RANGE = 20_000
/**
 * Time constant of the display smoothing in ms: the drawn position eases
 * toward the dead-reckoned target instead of snapping. Between ticks that
 * yields fluid motion; when a fresh fix corrects the extrapolation by
 * meters (or, after a data gap, by hundreds of meters), the ship glides
 * over in about a second instead of teleporting.
 */
const SMOOTH_TAU_MS = 400
/** Fallback dimensions for the many small craft without static data. */
const DEFAULT_LENGTH = 12
const DEFAULT_WIDTH = 4

/**
 * glTF hulls per AIS type group, generated by scripts/build-vehicle-models.mjs
 * from scripts/lib/vessel-fleet.mjs – same visual language as the vehicle
 * fleet. Reference dimensions mirror VESSEL_DIMS there (pinned against the
 * GLB bounds by tests/vessel-models.test.ts); the drawn ship is this model
 * stretched to the vessel's reported size, so one coaster hull covers
 * everything from a bunker barge to the 200 m CEMLUNA.
 */
export const VESSEL_MODELS: Record<string, { uri: string; length: number; width: number; height: number }> = {
  'vessel-cargo': { uri: 'models/vessel-cargo.glb', length: 90, width: 14, height: 16 },
  'vessel-tanker': { uri: 'models/vessel-tanker.glb', length: 90, width: 14, height: 14 },
  'vessel-passenger': { uri: 'models/vessel-passenger.glb', length: 160, width: 24, height: 34 },
  'vessel-tug': { uri: 'models/vessel-tug.glb', length: 26, width: 9, height: 10 },
  'vessel-fishing': { uri: 'models/vessel-fishing.glb', length: 18, width: 5.5, height: 7.5 },
  'vessel-sail': { uri: 'models/vessel-sail.glb', length: 12, width: 3.8, height: 14 },
  'vessel-motor': { uri: 'models/vessel-motor.glb', length: 14, width: 4.2, height: 5 },
  'vessel-generic': { uri: 'models/vessel-generic.glb', length: 16, width: 5, height: 5.5 },
}

/**
 * AIS ship type code → archetype model. Many vessels broadcast type 0 or
 * 9x "other" – for those the reported length decides: anything ship-sized
 * gets the cargo silhouette instead of a workboat stretched past all
 * plausibility (the 135 m VIKING HAKI is no dinghy).
 */
export function archetypeFor(typeCode: number, lengthM: number | null = null): string {
  const group = Math.floor(typeCode / 10)
  if (group === 6 || group === 4) return 'vessel-passenger' // 4x = high-speed craft
  if (group === 7) return 'vessel-cargo'
  if (group === 8) return 'vessel-tanker'
  if (group === 5) return 'vessel-tug' // tug/pilot/SAR/support
  if (typeCode === 31 || typeCode === 32) return 'vessel-tug' // towing
  if (typeCode === 30) return 'vessel-fishing'
  if (typeCode === 36) return 'vessel-sail'
  if (typeCode === 37) return 'vessel-motor'
  if ((group === 0 || group === 3 || group === 9) && (lengthM ?? 0) >= 45) return 'vessel-cargo'
  return 'vessel-generic'
}

/** Height scale from the footprint scale – ships do not grow linearly tall. */
function heightScale(lengthScale: number, widthScale: number): number {
  return Math.min(2.2, Math.max(0.55, Math.sqrt(lengthScale * widthScale)))
}

/** Hull color and height by AIS ship type group – muted, the fleet is scenery. */
function vesselStyle(typeCode: number): { color: string; height: number } {
  const group = Math.floor(typeCode / 10)
  if (group === 6) return { color: '#4a7fb5', height: 5 } // passenger
  if (group === 7) return { color: '#4e8a57', height: 5 } // cargo
  if (group === 8) return { color: '#a05252', height: 5 } // tanker
  if (typeCode === 30) return { color: '#8a7250', height: 3 } // fishing
  if (typeCode === 36 || typeCode === 37) return { color: '#8a6fb0', height: 3 } // sailing/pleasure
  if (group === 5) return { color: '#4f9494', height: 3 } // tug/pilot/SAR
  return { color: '#7a8494', height: 3 } // unknown
}

interface VesselRecord {
  /** Archetype the body was chosen by – a late type code swaps the hull. */
  archetype: string
  /** Placeholder box until the glTF hull is in (null afterwards). */
  primitive: Primitive | null
  /** glTF hull; null while loading (the box stands in) or after a failure. */
  model: Model | null
  /** The model's own matrix – fromGltfAsync clones what it got. */
  modelMatrix: Matrix4 | null
  /** Unscaled base pose; the model matrix composes scale on top. */
  matrix: Matrix4
  labelEntity: Entity
  labelPosition: ConstantPositionProperty
  /** Dimensions the box was built with – a real size arriving later rebuilds it. */
  builtLength: number
  builtWidth: number
  builtHeight: number
  labelText: string
  /** Smoothed pose actually drawn (eases toward the reckoned target). */
  displayPosition: Cartesian3
  displayBearing: number
  /** Pose as of the last repaint request – the change detector. */
  lastPosition: Cartesian3
  lastBearing: number
}

const positionScratch = new Cartesian3()
const hprScratch = new HeadingPitchRoll(0, 0, 0)
const scaleScratch = new Cartesian3()

/** Night-time window glow, identical language to the vehicle fleet. */
const WINDOW_GLOW_COLOR = 'vec3(1.0, 0.83, 0.52)'
const WINDOW_GLOW_LUMINANCE_CUTOFF = '0.075'
const WINDOW_GLOW_MAX = 0.85

export class VesselLayer {
  private vessels = new Map<number, VesselRecord>()
  private visible = true
  private frustumSphere = new BoundingSphere()
  private lastSyncMs = 0
  /** Lights the hulls' glazing at night (see WINDOW_GLOW_COLOR). */
  private readonly windowGlowShader = new CustomShader({
    uniforms: { u_windowGlow: { type: UniformType.FLOAT, value: 0 } },
    fragmentShaderText: `
      void fragmentMain(FragmentInput fsInput, inout czm_modelMaterial material)
      {
        float luminance = dot(material.diffuse, vec3(0.2126, 0.7152, 0.0722));
        if (luminance < ${WINDOW_GLOW_LUMINANCE_CUTOFF})
        {
          material.emissive += ${WINDOW_GLOW_COLOR} * u_windowGlow;
        }
      }
    `,
  })

  constructor(
    private readonly viewer: Viewer,
    private readonly host: VesselLayerHost,
  ) {}

  /**
   * Whether `position` sits inside the view and close enough to matter.
   * Everything the layer changes – movement, arrivals, departures, late
   * names and dimensions – is folded into whichever frame renders next
   * anyway; a repaint of its own is only owed while someone can see the
   * change. Off screen the layer stays silent, and the app's
   * event-driven rendering stays idle (the trams' rule).
   */
  private isOnScreen(
    cullingVolume: { computeVisibility(sphere: BoundingSphere): number },
    position: Cartesian3,
  ): boolean {
    if (!this.visible) return false
    if (Cartesian3.distance(this.viewer.camera.positionWC, position) >= VESSEL_RENDER_RANGE) return false
    Cartesian3.clone(position, this.frustumSphere.center)
    this.frustumSphere.radius = 80
    return cullingVolume.computeVisibility(this.frustumSphere) !== Intersect.OUTSIDE
  }

  private repaintIfOnScreen(
    cullingVolume: { computeVisibility(sphere: BoundingSphere): number },
    position: Cartesian3,
  ): void {
    if (this.isOnScreen(cullingVolume, position)) this.host.requestRender()
  }

  /**
   * Per-tick update: dead-reckoned positions, arrivals, departures.
   * Returns whether a vessel whose drawn pose is still changing sits
   * inside the view – the app's tick and render pacing treat that like a
   * tram in view, otherwise ships glide in 500 ms stop-motion steps.
   */
  sync(vessels: AisVessel[], nowMs: number): { anyMovingVesselInView: boolean } {
    const alive = new Set<number>()
    // One culling volume per tick, for every repaint decision below.
    const camera = this.viewer.camera
    const cullingVolume = camera.frustum.computeCullingVolume(
      camera.positionWC,
      camera.directionWC,
      camera.upWC,
    )
    // Smoothing step for this tick; a long pause (tab hidden) snaps.
    const dtMs = this.lastSyncMs > 0 ? Math.max(0, nowMs - this.lastSyncMs) : 0
    this.lastSyncMs = nowMs
    const alpha = dtMs > 0 && dtMs < 2000 ? 1 - Math.exp(-dtMs / SMOOTH_TAU_MS) : 1

    let anyMovingVesselInView = false
    for (const vessel of vessels) {
      if (nowMs - vessel.positionAt > AIS_EXPIRE_MS) continue
      alive.add(vessel.mmsi)

      let record = this.vessels.get(vessel.mmsi)
      // Static data can land after the first position: a type code picks
      // a different hull, and while the box still stands in, clearly
      // different dimensions rebuild it. A loaded model needs neither –
      // its per-tick scale follows the reported size by itself.
      if (
        record &&
        (record.archetype !== archetypeFor(vessel.typeCode, vessel.lengthM) ||
          (record.model === null &&
            (Math.abs((vessel.lengthM ?? DEFAULT_LENGTH) - record.builtLength) > 1 ||
              Math.abs((vessel.widthM ?? DEFAULT_WIDTH) - record.builtWidth) > 1)))
      ) {
        this.remove(vessel.mmsi)
        record = undefined
      }
      if (!record) {
        record = this.createVessel(vessel, nowMs)
        this.vessels.set(vessel.mmsi, record)
        this.repaintIfOnScreen(cullingVolume, record.lastPosition)
      }

      const reckoned = deadReckon(vessel, nowMs)
      // Stretch the archetype to the reported size; the box placeholder
      // was already built at it. Height grows with the footprint's root –
      // ships get longer much faster than they get taller.
      const spec = VESSEL_MODELS[record.archetype]
      const lengthScale = (vessel.lengthM ?? DEFAULT_LENGTH) / spec.length
      const widthScale = (vessel.widthM ?? DEFAULT_WIDTH) / spec.width
      const drawnHeight = record.model
        ? spec.height * heightScale(lengthScale, widthScale)
        : record.builtHeight
      const target = Cartesian3.fromDegrees(
        reckoned.lon,
        reckoned.lat,
        this.host.waterSurfaceHeight + drawnHeight / 2,
        undefined,
        positionScratch,
      )
      Cartesian3.lerp(record.displayPosition, target, alpha, record.displayPosition)
      if (Cartesian3.equalsEpsilon(record.displayPosition, target, 0, 0.05)) {
        Cartesian3.clone(target, record.displayPosition)
      }
      // Shortest-path ease of the bearing – cog jitter must not wag the bow
      const bearingGap = ((reckoned.bearingDeg - record.displayBearing + 540) % 360) - 180
      record.displayBearing =
        Math.abs(bearingGap) < 0.05
          ? reckoned.bearingDeg
          : (record.displayBearing + bearingGap * alpha + 360) % 360

      hprScratch.heading = CesiumMath.toRadians(record.displayBearing - 90)
      Transforms.headingPitchRollToFixedFrame(
        record.displayPosition,
        hprScratch,
        undefined,
        undefined,
        record.matrix,
      )
      if (record.model && record.modelMatrix) {
        // Model frame after Cesium's glTF mapping: x = travel, y = beam,
        // z = up. Written into the model's own matrix instance.
        scaleScratch.x = lengthScale
        scaleScratch.y = widthScale
        scaleScratch.z = heightScale(lengthScale, widthScale)
        Matrix4.multiplyByScale(record.matrix, scaleScratch, record.modelMatrix)
      }
      record.labelPosition.setValue(record.displayPosition)
      // Repaint per tick while the drawn pose still changes – that is what
      // makes a ship under way glide at the render loop's own rate.
      const poseChanged =
        !Cartesian3.equalsEpsilon(record.displayPosition, record.lastPosition, 0, 0.02) ||
        Math.abs(record.displayBearing - record.lastBearing) > 0.05
      // The pacing signal must NOT hang on the per-tick repaint epsilon:
      // a slow ship advances less than it per 33 ms tick, the flag would
      // drop, the app would fall back to 500 ms ticks, and the two rates
      // would oscillate into exactly the stop-motion this exists to
      // prevent. "Under way" comes from the data instead – stable across
      // ticks – with the pose ease riding along until it converged.
      const underWay =
        (vessel.sogKn ?? 0) >= 0.3 &&
        vessel.cogDeg !== null &&
        nowMs - vessel.positionAt <= AIS_RECKON_CAP_MS
      if ((poseChanged || underWay) && this.isOnScreen(cullingVolume, record.displayPosition)) {
        anyMovingVesselInView = true
        if (poseChanged) this.host.requestRender()
      }
      if (poseChanged) {
        Cartesian3.clone(record.displayPosition, record.lastPosition)
        record.lastBearing = record.displayBearing
      }

      const text = vessel.name || String(vessel.mmsi)
      if (text !== record.labelText && record.labelEntity.label) {
        record.labelText = text
        record.labelEntity.label.text = new ConstantProperty(text)
        this.repaintIfOnScreen(cullingVolume, record.lastPosition)
      }
    }

    for (const [mmsi, record] of this.vessels) {
      if (!alive.has(mmsi)) {
        // Position first – remove() drops the record.
        this.repaintIfOnScreen(cullingVolume, record.lastPosition)
        this.remove(mmsi)
      }
    }
    return { anyMovingVesselInView }
  }

  /** Day→night ramp for the window glow (driven by the map's sun state). */
  applyNightFactor(night: number): void {
    this.windowGlowShader.setUniform('u_windowGlow', WINDOW_GLOW_MAX * night)
  }

  /** The underground view hides the surface fleet with the other layers. */
  setVisible(visible: boolean): void {
    if (visible === this.visible) return
    this.visible = visible
    for (const record of this.vessels.values()) {
      if (record.primitive) record.primitive.show = visible
      if (record.model) record.model.show = visible
      record.labelEntity.show = visible
    }
    this.host.requestRender()
  }

  get vesselCount(): number {
    return this.vessels.size
  }

  private createVessel(vessel: AisVessel, nowMs: number): VesselRecord {
    const archetype = archetypeFor(vessel.typeCode, vessel.lengthM)
    const style = vesselStyle(vessel.typeCode)
    const length = vessel.lengthM ?? DEFAULT_LENGTH
    const width = vessel.widthM ?? DEFAULT_WIDTH
    const reckoned = deadReckon(vessel, nowMs)
    const position = Cartesian3.fromDegrees(
      reckoned.lon,
      reckoned.lat,
      this.host.waterSurfaceHeight + style.height / 2,
    )
    const matrix = Transforms.headingPitchRollToFixedFrame(
      position,
      new HeadingPitchRoll(CesiumMath.toRadians(reckoned.bearingDeg - 90), 0, 0),
    )
    const color = Color.fromCssColorString(style.color)
    const primitive = new Primitive({
      geometryInstances: new GeometryInstance({
        geometry: BoxGeometry.fromDimensions({
          vertexFormat: PerInstanceColorAppearance.VERTEX_FORMAT,
          dimensions: new Cartesian3(length, width, style.height),
        }),
        attributes: { color: ColorGeometryInstanceAttribute.fromColor(color) },
        id: `vessel:${vessel.mmsi}`,
      }),
      appearance: new PerInstanceColorAppearance({ closed: true, translucent: false }),
      asynchronous: false,
      modelMatrix: matrix,
    })
    primitive.show = this.visible
    this.viewer.scene.primitives.add(primitive)

    const labelPosition = new ConstantPositionProperty(position)
    const labelText = vessel.name || String(vessel.mmsi)
    const labelEntity = this.viewer.entities.add({
      id: `vessel:${vessel.mmsi}`,
      position: labelPosition,
      show: this.visible,
      label: {
        text: labelText,
        font: '10px "Inter Variable", system-ui, sans-serif',
        fillColor: Color.WHITE,
        outlineColor: color,
        outlineWidth: 2,
        style: LabelStyle.FILL_AND_OUTLINE,
        pixelOffset: new Cartesian2(0, -16),
        distanceDisplayCondition: new DistanceDisplayCondition(0, NAME_VISIBLE_RANGE),
        disableDepthTestDistance: Number.POSITIVE_INFINITY,
      },
    })

    const record: VesselRecord = {
      archetype,
      // Primitive CLONES the modelMatrix passed in – reference its own
      // instance so the in-place updates in sync() actually move the box.
      primitive,
      model: null,
      modelMatrix: null,
      matrix: primitive.modelMatrix,
      labelEntity,
      labelPosition,
      builtLength: length,
      builtWidth: width,
      builtHeight: style.height,
      labelText,
      displayPosition: Cartesian3.clone(position),
      displayBearing: reckoned.bearingDeg,
      lastPosition: Cartesian3.clone(position),
      lastBearing: reckoned.bearingDeg,
    }
    void this.attachModel(record, vessel.mmsi)
    return record
  }

  /**
   * Swaps the placeholder box for the archetype's glTF hull once it is
   * in. A failed load (offline, tests) keeps the box – the fleet stays
   * visible either way.
   */
  private async attachModel(record: VesselRecord, mmsi: number): Promise<void> {
    const spec = VESSEL_MODELS[record.archetype]
    let model: Model
    try {
      model = await Model.fromGltfAsync({
        url: `${import.meta.env.BASE_URL}${spec.uri}`,
        id: `vessel:${mmsi}`,
        modelMatrix: Matrix4.clone(record.matrix),
      })
    } catch (error) {
      console.warn('[MiniRostock3D] Vessel model failed to load:', error)
      return
    }
    // The vessel may have expired (or the viewer been torn down) meanwhile
    if (this.viewer.isDestroyed() || this.vessels.get(mmsi) !== record) {
      model.destroy()
      return
    }
    model.customShader = this.windowGlowShader
    model.show = this.visible
    this.viewer.scene.primitives.add(model)
    if (record.primitive) {
      this.viewer.scene.primitives.remove(record.primitive)
      record.primitive = null
    }
    record.model = model
    // fromGltfAsync clones the matrix – rebind so the in-place scale
    // composition in sync() reaches the model.
    record.modelMatrix = model.modelMatrix
    this.host.requestRender()
  }

  private remove(mmsi: number): void {
    const record = this.vessels.get(mmsi)
    if (!record) return
    if (record.primitive) this.viewer.scene.primitives.remove(record.primitive)
    if (record.model) this.viewer.scene.primitives.remove(record.model)
    this.viewer.entities.remove(record.labelEntity)
    this.vessels.delete(mmsi)
  }
}
