#!/usr/bin/env node
/**
 * Post-processes src/cities/<slug>/network.json in place: simplifies all
 * direction paths (Douglas–Peucker, default 0.3 m tolerance) and rounds
 * coordinates to 6 decimal places (~11 cm). Visually lossless, but shrinks
 * the data chunk and speeds up network preparation at startup.
 *
 *   npm run data:simplify -- --city rostock     (no --city: every city)
 *
 * Environment variables:
 *   CITY                  – the city, like --city
 *   NETWORK_OUT           – alternative network.json path (one city only)
 *   SIMPLIFY_TOLERANCE_M  – tolerance in meters (default 0.3)
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { forEachRequestedCity } from './lib/city.mjs'
import { compactPath, DEFAULT_TOLERANCE_M } from './lib/simplify.mjs'

const TOLERANCE = Number(process.env.SIMPLIFY_TOLERANCE_M) || DEFAULT_TOLERANCE_M

function simplify(FILE) {
const network = JSON.parse(readFileSync(FILE, 'utf8'))

let before = 0
let after = 0
let droppedHeights = false
for (const line of network.lines) {
  for (const dir of line.directions) {
    before += dir.path.length
    dir.path = compactPath(dir.path, TOLERANCE)
    after += dir.path.length
    // Heights are per vertex – once simplification changes the vertex list
    // they no longer line up and must be regenerated by data:heights.
    if (dir.heights && dir.heights.length !== dir.path.length) {
      delete dir.heights
      droppedHeights = true
    }
  }
}
for (const stop of Object.values(network.stops)) {
  stop.coord = [Number(stop.coord[0].toFixed(6)), Number(stop.coord[1].toFixed(6))]
}

writeFileSync(FILE, JSON.stringify(network, null, 2) + '\n', 'utf8')
console.log(
  `✅ ${FILE}: path points ${before} → ${after} ` +
    `(-${(100 - (after / before) * 100).toFixed(1)} %, tolerance ${TOLERANCE} m)`,
)
if (droppedHeights) {
  console.warn(
    '⚠ Route heights no longer matched the simplified paths and were removed – ' +
      'run "npm run data:heights" to regenerate them.',
  )
}
console.log('Tip: npm test validates the simplified dataset.')
}

forEachRequestedCity((_city, paths) =>
  simplify(process.env.NETWORK_OUT ? resolve(process.env.NETWORK_OUT) : paths.network),
).catch((err) => {
  console.error('❌ Error:', err.message)
  process.exit(1)
})
