/**
 * A city's airfield lighting, generated by scripts/fetch-airfield-lights.mjs
 * from OpenStreetMap with terrain heights from the same source the route
 * heights come from. Loaded per city by src/cities/index.ts, drawn at
 * night by src/map/AirfieldLightsLayer.ts.
 */

/** The colours a light wears – the ones ICAO gives the kinds (see scripts/lib/airfield-lights.mjs). */
export type AirfieldLightColour = 'white' | 'green' | 'red' | 'blue' | 'yellow'

/**
 * One light: [longitude, latitude, terrain height in meters NHN, kind,
 * colour]. The kind is OSM's navigationaid value (rwe, rwc, rwt, tdz,
 * als, papi, txe, txc, sbl, cbl, rgl …); the colour is what the map
 * draws.
 */
export type AirfieldLight = [number, number, number, string, AirfieldLightColour]

export interface AirfieldLightData {
  meta: {
    attribution: string
    /** The terrain line inside `attribution` – the pipeline reuses heights only under the same one. */
    terrainAttribution?: string
  }
  lights: AirfieldLight[]
}
