/**
 * A city's buoys, generated by scripts/fetch-buoys.mjs from
 * OpenStreetMap's seamark tagging. Loaded per city by src/cities/index.ts,
 * drawn on the water – clamped to the tiles, lit at night – by
 * src/map/BuoysLayer.ts.
 */

/** The colours the map has a buoy for (see scripts/lib/buoys.mjs for what stays out). */
export type BuoyColour = 'red' | 'green' | 'yellow'
/** The shapes the map has a model for, as OSM spells them. */
export type BuoyShape = 'can' | 'conical' | 'spar' | 'pillar' | 'spherical' | 'barrel'
/** The colours a buoy's lantern can show. */
export type BuoyLightColour = 'red' | 'green' | 'yellow' | 'white'

/**
 * One buoy: [longitude, latitude, colour, shape, light colour, light
 * character, light period in seconds] – the three light fields null for
 * an unlit buoy. The character (Fl, Q, Oc, Iso …) and the period are
 * carried as OSM has them; the map lights every lantern steadily for
 * now (see BuoysLayer). No height: the buoy floats on the tiles' water.
 */
export type Buoy = [
  number,
  number,
  BuoyColour,
  BuoyShape,
  BuoyLightColour | null,
  string | null,
  number | null,
]

export interface BuoyData {
  meta: {
    attribution: string
  }
  buoys: Buoy[]
}
