/**
 * A city's lighthouses and lesser fixed lights, generated by
 * scripts/fetch-lighthouses.mjs from OpenStreetMap's seamark tagging.
 * Loaded per city by src/cities/index.ts, drawn on top of the towers
 * Google's tiles carry – lit at night – by src/map/LighthousesLayer.ts.
 */

/** The colours a light can show. */
export type LightColour = 'white' | 'red' | 'green' | 'yellow'
/** A harbour's tower (light_major, or a range of ten miles and more) or a pier head, a leading light. */
export type LighthouseKind = 'major' | 'minor'

/**
 * One lit sector: [colour, start bearing, end bearing, character]. The
 * bearings are from seaward – from the vessel to the light, clockwise
 * from true north – and null for an all-round light. The character
 * (Fl, Oc, Iso …) is carried as OSM has it; the map shows every light
 * steadily for now (see LighthousesLayer).
 */
export type LightSector = [LightColour, number | null, number | null, string | null]

/**
 * One light: [longitude, latitude, kind, elevation of the light over the
 * water in metres (null where OSM has none), range in nautical miles
 * (null likewise), sectors]. No terrain height: the map sets the light
 * on the top of its tower as the tiles have it.
 */
export type Lighthouse = [number, number, LighthouseKind, number | null, number | null, LightSector[]]

export interface LighthouseData {
  meta: {
    attribution: string
  }
  lights: Lighthouse[]
}
