/**
 * A city's lighthouses and lesser fixed lights, generated by
 * scripts/fetch-lighthouses.mjs from OpenStreetMap's seamark tagging.
 * Loaded per city by src/cities/index.ts, drawn on top of the towers
 * Google's tiles carry – lit at night – by src/map/LighthousesLayer.ts.
 */

/** The colours a light can show. */
export type LightColour = 'white' | 'red' | 'green' | 'yellow'
/** A harbour's tower (light_major, or a range of ten miles and more) or a pier head, a leading light. */
export type LighthouseKind = 'major' | 'minor'

/**
 * One lit sector: [colour, start bearing, end bearing, character,
 * period, group]. The bearings are from seaward – from the vessel to the
 * light, clockwise from true north – and null for an all-round light.
 * The character (Fl, Oc, Iso …) is carried as OSM has it, with the
 * light's period in seconds and its group ("3", "2+1": the flashes a
 * period holds), null where OSM has none; the two trailing elements are
 * absent in a file written before they were added. A major light flashing
 * with a known period is a rotating optic, and the map turns its beam
 * (see lib/lighthouse-beam.ts); every other light shows steadily.
 */
export type LightSector = [
  LightColour,
  number | null,
  number | null,
  string | null,
  (number | null)?,
  (string | null)?,
]

/**
 * One light: [longitude, latitude, kind, elevation of the light over the
 * water in metres (null where OSM has none), range in nautical miles
 * (null likewise), sectors]. No terrain height: the map sets the light
 * on the top of its tower as the tiles have it.
 */
export type Lighthouse = [number, number, LighthouseKind, number | null, number | null, LightSector[]]

export interface LighthouseData {
  meta: {
    attribution: string
  }
  lights: Lighthouse[]
}
