import type { LonLat } from '@/lib/geo'

/** Transit mode of a line. If the field is missing in network.json, 'tram' applies. */
export type TransitMode = 'tram' | 'bus' | 'ferry'

/** Vehicle dimensions in meters (length × width × height). */
export interface VehicleDimensions {
  length: number
  width: number
  height: number
}

/** Raw format of src/data/network.json (generated by the data scripts). */
export interface NetworkJson {
  meta: NetworkMeta
  stops: Record<string, StopJson>
  lines: LineJson[]
}

export interface NetworkMeta {
  /** "approximated" = bundled demo geometry, "osm" = generated via Overpass. */
  source: 'approximated' | 'osm'
  generated: string
  attribution: string
}

export interface StopJson {
  name: string
  coord: LonLat
}

export interface LineJson {
  id: string
  name: string
  color: string
  /** Transit mode; missing = 'tram' (older network.json files). */
  mode?: TransitMode
  /** Line-specific vehicle dimensions (e.g. ferries); missing = mode default. */
  vehicle?: VehicleDimensions
  /**
   * One or two directions. With only one direction, the opposite direction
   * is generated automatically by mirroring the path.
   */
  directions: DirectionJson[]
}

export interface DirectionJson {
  from: string
  to: string
  path: LonLat[]
  /** Stop ids in travel order. */
  stops: string[]
}

/** Prepared network with precomputed distances. */
export interface PreparedNetwork {
  meta: NetworkMeta
  lines: PreparedLine[]
  lineById: Map<string, PreparedLine>
}

export interface PreparedLine {
  id: string
  name: string
  color: string
  mode: TransitMode
  /** Resolved vehicle dimensions (line-specific or mode default). */
  vehicle: VehicleDimensions
  directions: [PreparedDirection, PreparedDirection]
}

export interface PreparedStop {
  id: string
  name: string
  coord: LonLat
  /** Distance of the stop along the direction path in meters. */
  dist: number
}

export interface PreparedDirection {
  lineId: string
  direction: 0 | 1
  from: string
  to: string
  path: LonLat[]
  cum: number[]
  totalLength: number
  stops: PreparedStop[]
}
