import type { LonLat } from '@/lib/geo'
import type { TunnelRange } from '@/lib/tunnels'

/** Transit mode of a line. If the field is missing in network.json, 'tram' applies. */
export type TransitMode = 'tram' | 'train' | 'bus' | 'ferry'

/** Vehicle dimensions in meters (length × width × height). */
export interface VehicleDimensions {
  length: number
  width: number
  height: number
}

/** Raw format of src/data/network.json (generated by the data scripts). */
export interface NetworkJson {
  meta: NetworkMeta
  stops: Record<string, StopJson>
  lines: LineJson[]
}

export interface NetworkMeta {
  /** "approximated" = bundled demo geometry, "osm" = generated via Overpass. */
  source: 'approximated' | 'osm'
  generated: string
  attribution: string
}

export interface StopJson {
  name: string
  coord: LonLat
  /** Terrain height in meters NHN (DGM, © GeoBasis-DE/M-V); missing = unknown. */
  nhn?: number
}

export interface LineJson {
  id: string
  name: string
  color: string
  /** Transit mode; missing = 'tram' (older network.json files). */
  mode?: TransitMode
  /** Line-specific vehicle dimensions (e.g. ferries); missing = mode default. */
  vehicle?: VehicleDimensions
  /**
   * One or two directions. With only one direction, the opposite direction
   * is generated automatically by mirroring the path.
   */
  directions: DirectionJson[]
}

export interface DirectionJson {
  from: string
  to: string
  path: LonLat[]
  /** Stop ids in travel order. */
  stops: string[]
  /**
   * Tunnel/underground sections as [start, end] meter ranges along `path`
   * (from OSM: tunnel=*, location=underground, or a negative layer).
   * Missing or empty = the whole direction runs above ground.
   */
  tunnels?: TunnelRange[]
  /**
   * Bridge sections as [start, end] meter ranges along `path` (OSM
   * bridge=*). Only consumed by the data pipeline (bridge decks are
   * interpolated into `heights` there); the runtime ignores them.
   */
  bridges?: [number, number][]
  /**
   * Terrain height per path vertex in meters NHN (DGM © GeoBasis-DE/M-V,
   * bridge decks interpolated). Missing = draw routes clamped to ground.
   */
  heights?: number[]
}

/** Prepared network with precomputed distances. */
export interface PreparedNetwork {
  meta: NetworkMeta
  lines: PreparedLine[]
  lineById: Map<string, PreparedLine>
}

export interface PreparedLine {
  id: string
  name: string
  color: string
  mode: TransitMode
  /** Resolved vehicle dimensions (line-specific or mode default). */
  vehicle: VehicleDimensions
  directions: [PreparedDirection, PreparedDirection]
}

export interface PreparedStop {
  id: string
  name: string
  coord: LonLat
  /** Distance of the stop along the direction path in meters. */
  dist: number
  /** Terrain height in meters NHN; basis for the route height calibration. */
  nhn?: number
}

export interface PreparedDirection {
  lineId: string
  direction: 0 | 1
  from: string
  to: string
  path: LonLat[]
  cum: number[]
  totalLength: number
  stops: PreparedStop[]
  /** Normalized tunnel sections (sorted, merged, clamped); [] = none. */
  tunnels: TunnelRange[]
  /**
   * Terrain height per path vertex (meters NHN), validated against the
   * path length; undefined = clamp routes to the 3D tiles instead.
   */
  heights?: number[]
}
