/**
 * Rostock's street lamps along the transit routes, generated by
 * scripts/fetch-street-lamps.mjs from OpenStreetMap (the city's official
 * open-data import) with terrain heights from the same DGM the route
 * heights come from.
 */

import raw from './street-lamps.json'

/** One lamp: [longitude, latitude, terrain height in meters NHN]. */
export type StreetLamp = [number, number, number]

export interface StreetLampData {
  meta: {
    attribution: string
    /** Distance to a route within which a lamp was kept, in meters. */
    maxDistanceMeters: number
    /** Minimum spacing the set was thinned to (0 = every lamp kept). */
    minSpacingMeters: number
  }
  lamps: StreetLamp[]
}

export function loadStreetLamps(): StreetLampData {
  return raw as StreetLampData
}
