/**
 * A city's street lamps along its transit routes, generated by
 * scripts/fetch-street-lamps.mjs from OpenStreetMap with terrain heights
 * from the same source the route heights come from. Loaded per city by
 * src/cities/index.ts.
 */

/** One lamp: [longitude, latitude, terrain height in meters NHN]. */
export type StreetLamp = [number, number, number]

export interface StreetLampData {
  meta: {
    attribution: string
    /** The terrain line inside `attribution` – the pipeline reuses heights only under the same one. */
    terrainAttribution?: string
    /** Distance to a route within which a lamp was kept, in meters. */
    maxDistanceMeters: number
    /** Minimum spacing the set was thinned to (0 = every lamp kept). */
    minSpacingMeters: number
  }
  lamps: StreetLamp[]
}
